config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('page.urls')),
    path('admin/', admin.site.urls),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

page/urls.py
from django.urls import path
from . import views

app_name = 'page'

urlpatterns = [
    path('post/<int:pk>/', views.post_detail, name='post_detail'),
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
    path('science/', views.science, name='science'),
    path('business/', views.business, name='business'),
    path('career/', views.career, name='career'),
    path('product/', views.product, name='product'),
    path('plan/', views.plan, name='plan'),
]

page/models.py
from django.db import models
from django.utils import timezone
from django.conf import settings

class Post(models.Model):
    author = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    text = models.TextField()
    category = models.CharField(max_length=10)
    created_date = models.DateTimeField(
        default=timezone.now)
    published_date = models.DateTimeField(
        blank=True, null=True)

    def publish(self):
        self.published_date = timezone.now()
        self.save()
    
    def __str__(self):
        return self.title

page/views.py
from django.shortcuts import render, get_object_or_404
from .models import Post

def index(request):
    posts = Post.objects.all()
    context = {
        'posts': posts
        }
    return render(request, 'page/index.html', context)

def post_detail(request, pk):
    post = get_object_or_404(Post, pk=pk)
    return render(request, 'page/post_detail.html', {'post': post})

def about(request):
    return render(request, 'page/about.html')

def business(request):
    return render(request, 'page/business.html')

def science(request):
    return render(request, 'page/science.html')

def product(request):
    return render(request, 'page/product.html')

def career(request):
    return render(request, 'page/career.html')

def plan(request):
    return render(request, 'page/plan.html')

page/templates/page/about.html
{% extends "page/base.html" %} 
{% load static %} 
{% block content %}
<section class="">
            <div class="container mx-auto flex px-10 py-8 items-center justify-center flex-col">
                <img class="lg:w-15/15 md:w-15/5 w-20/6 mb-10 object-cover object-center rounded" alt="hero"
                    src="{% static 'img/aboutus.jpg'%}">
            </div>
        </section>
        <section class="">
            <div class="container px-5 py-8 mx-auto flex flex-wrap">
                <div class="flex flex-col text-center w-full mb-20">
                    <h2 class="text-xs text-black tracking-widest font-medium title-font mb-1">대한민국 대표 바이오기업</h2>
                    <h1 class="sm:text-3xl text-2xl font-medium title-font text-black">FastFowardBio
                    </h1>
                </div>
                <div class="flex flex-wrap -m-4">
                    <div class="p-4 md:w-1/2">
                        <div class="flex rounded-lg h-full bg-gray-20 p-8 flex-col">
                            <div class="flex items-center mb-3">
                                <h2 class="text-gray-700 text-lg title-font font-black ">기업 개요</h2>
                            </div>
                            <div class="flex-grow">
                                <p class="leading-relaxed text-gray-700 font-medium"> 남들이 가지않은 길을 개척하며 눈부신 성과를 일궈온 FastFowardBio는 케미컬의약품과 신약개발, U-헬스케어 플랫폼 사업 등 차별화된 사업 전략을 기반으로 글로벌 생명공학 기업으로 지속 성장해나갈 것입니다.</p>
                                <a class="mt-3 text-gray-700 inline-flex items-center font-medium" href='#'>
                                Learn More »
                                </a>
                            </div>
                        </div>
                    </div>
                    <div class="p-4 md:w-1/2">
                           <div class="flex rounded-lg h-full bg-gray-20 p-8 flex-col">
                            <div class="flex items-center mb-3">
                                <h2 class="text-gray-700 text-lg title-font font-black ">비전</h2>
                            </div>
                            <div class="flex-grow">
                                <p class="leading-relaxed text-gray-700 font-medium">FastFowardBio는 차세대 바이오의약품 및 케미컬의약품 개발을 통해 인류의 건강과 복지 증진의 가치를 실현하는 세계적인 종합생명공학 기업으로    성장해나가겠습니다.</p>
                                <a class="mt-3 text-gray-700 inline-flex items-center font-medium" href='#'>
                                Learn More »
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
                <section class="">
            <div class="container px-5 py-24 mx-auto flex flex-wrap">
                <div class="flex flex-col text-center w-full mb-20">
                    <h2 class="text-xs text-black tracking-widest font-medium title-font mb-1">기술과 혁신으로 인류의 삶을 풍요롭게 하고자 합니다.</h2>
                    <h1 class="sm:text-3xl text-2xl font-medium title-font text-black">핵심가치 & 사업전략
                    </h1>
                </div>
                <div class="flex flex-wrap -m-4">
                    <div class="p-4 md:w-1/3">
                        <div class="flex rounded-lg h-full bg-gray-200 p-8 flex-col">
                            <div class="flex items-center mb-3">
                                <h2 class="text-gray-700 text-lg title-font font-bold">인재 혁신</h2>
                            </div>
                            <div class="flex-grow">
                                <p class="leading-relaxed text-gray-700 font-medium">직원에게 재능을 더욱 발전시키고 다섯가지 핵심 가치를 실현할 수 있도록 적극적으로 격려하며 지원하고 있습니다.</p>
                            </div>
                        </div>
                    </div>
                    <div class="p-4 md:w-1/3">
                           <div class="flex rounded-lg h-full bg-gray-200 p-8 flex-col">
                            <div class="flex items-center mb-3">
                                <h2 class="text-gray-700 text-lg title-font font-bold">프로세스 혁신</h2>
                            </div>
                            <div class="flex-grow">
                                <p class="leading-relaxed text-gray-700 font-medium">프로세스 혁신이란 습관적 관행을 뛰어 넘는 최상의 제조 수준을 목표로 삼고 끊임없이 노력함으로써 최고의 품질과 서비스를 약속하는 고객 지향적 혁신을 뜻합니다.</p>
                            </div>
                        </div>
                    </div>
                    <div class="p-4 md:w-1/3">
                           <div class="flex rounded-lg h-full bg-gray-200 p-8 flex-col">
                            <div class="flex items-center mb-3">
                                <h2 class="text-gray-700 text-lg title-font font-bold">포트폴리오 혁신</h2>
                            </div>
                            <div class="flex-grow">
                                <p class="leading-relaxed text-gray-700 font-medium">포트폴리오 혁신은 현재 우리가 영위하는 CMO 사업을 넘어, CDO 및 CRO 사업에 이르기까지 지속적으로 서비스를 확장하는 것에서 시작합니다.</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
{% endblock content %}

page/templates/page/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <!--
    ________________________________________________________________
    // seychelles
    // Product: https://demo.wickedtemplates.com/seychelles/seychelles.html
    // Built by https://wickedtemplates.com
    // The above copyright notice and this permission notice shall be included in all copies.
    --------------------------------------------------------------
    // Copyright 2020 Wicked Templates by Michael Andreuzza  Twitter: @Mike_Andreuzza (https://www.wickedtemplates.com)
    ________________________________________________________________
    -->
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
                <meta name="theme-color" content="#0a165c">
        <title>FastFowordBio</title>
        <link href="https://unpkg.com/tailwindcss@^1.0/dist/tailwind.min.css" rel="stylesheet">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.0/jquery.min.js"></script>
        <link href="https://fonts.googleapis.com/css2?family=Nanum+Gothic&display=swap" rel="stylesheet">
        <style>
        body {
            font-family: 'Nanum Gothic', sans-serif;
        }
        </style>
        <link rel="shortcut icon" type="image/png" href="{% static 'favicon.ico' %}"/>
    </head>
    <body>
	{% include "page/nav.html" %}
	{% block content%}
	{% endblock content%}
	{% include "page/footer.html" %}
	</body>
</html>

page/templates/page/business.html
{% extends "page/base.html" %} {% load static %} {% block content %}
<section class="text-black">
  <div
    class="container mx-auto flex px-5 pt-24 items-center justify-center flex-col"
  >
    <div class="text-center lg:w-2/3 w-full">
      <h1
        class="title-font sm:text-4xl text-3xl mb-4 font-medium text-black font-mono"
      >
        Biosimilar
      </h1>
      <p class="leading-relaxed mb-8 font-normal">
        환자들에게 합리적 비용의 고품질 바이오의약품 치료기회를 제공합니다.
      </p>
      <div class="flex justify-center">
        <button
          class="border-2 border-white text-white block rounded-sm font-bold py-4 px-6 mr-2 flex items-center hover:bg-gray-900 hover:text-pink-500 transition ease-in-out duration-700 mb-20"
        >
          Show me
        </button>
      </div>
    </div>
  </div>
</section>
<style>
  .bg-dots{
    background-image: url(https://assets-global.website-files.com/5b5a66e9f3166b36708705fa/5dea7a12bb83ab1f13040de5_cx-dots.svg);
    background-repeat: no-repeat
  }
</style>

<div class="bg-gray-100 m-auto max-w-6xl p-12">
   <div class="flex flex-col md:flex-row">
      <div class="md:w-1/2 max-w-md flex flex-col justify-center">
         <div class="md:text-5xl text-2xl uppercase font-black">
         퍼스트 무버를 넘어 게임 체인저로</div>
         <div class="text-xl mt-4">세계 최초로 항체 바이오시밀러인 시마를 글로벌 시장에 선보이며 합리적인 비용으로 더 많은 환자에게 치료 혜택을 제공함으로써 사회경제적 혁신을 이루었습니다. </div>
         <div class="my-5 h-16">
            <div class="shadow-md font-medium py-2 px-4 text-yellow-100
               cursor-pointer bg-red-400 hover:bg-red-500 rounded text-lg text-center w-48">자세히 알아보기</div>
         </div>
      </div>

      <div class="flex md:justify-end w-full md:w-1/2 -mt-5">
         <div class="">
            <div class="shadow-2xl max-w-md z-10 rounded-full mt-6 ml-4">
               <img alt="card img" class="rounded-t" src="{% static 'img/card_img.jpg'%}"> 
               <div class="text-2xl p-10 bg-white"><img alt="quote" class="float-left mr-1" src="https://assets-global.website-files.com/5b5a66e9f3166b36708705fa/5cf8fb1f994fb7168d0d66fb_quote-intro.svg"> 누적 처방 기록과 장기 임상 결과를 통해 효능과 안전성을 입증한 시마는 전세계 의약품 규제 기관과 환자의 신뢰를 받고있는 최초의 항체 바이오시밀러입니다. </div>
            </div>
         </div>
      </div>
   </div>
</div>
{% endblock %}

page/templates/page/careers.html
{% extends "page/base.html" %} 
{% load static %} 
{% block content %}
<section class="">
  <div
    class="container mx-auto flex px-10 py-8 items-center justify-center flex-col"
  >
    <h1 class="text-gray-700 text-6xl title-font font-black">
      Wow, such a empty!
    </h1>
  </div>
</section>

개인적으로나 전문적으로 성장할수 있는 기회가 있습니다.

인재상 

해당 분야 최고의 전문성과 함께 실행력을 발휘하고, 협업을 통해 집단지성을 추구하여 능력을 발전시키는 글로벌 인재 

지원 대상별 채용 절차

채용절차


    지원서 접수
    직무적합성평가
    삼성직무적성검사
    면접
    채용검진

지원 자격


    공고에 명시되어있는 시점에 입사 가능한 자
    어학 자격 보유자 (OPIc IM/TOEIC Speaking lv.6 이상)
    병역 필 또는 면제자로 해외여행에 결격사유가 없는 자


지원 하기

    삼성 채용 홈페이지에서 채용공고 확인과 지원이 가능합니다.

바로가기 

{% endblock %}

page/templates/page/index.html
{% extends "page/base.html" %}
{% load static %}
{% block content %}

        <section class="text-black">
            <div class="container mx-auto flex px-5 pt-24 items-center justify-center flex-col">
                <div class="text-center lg:w-2/3 w-full">
                    <h1 class="title-font sm:text-4xl text-3xl mb-4 font-medium	 text-black font-mono">
                        FastFowardBio</h1>
                    <p class="leading-relaxed mb-8 font-normal">
                    인류의 더 건강하고 행복한 삶을 위한 우리의 도전은 계속됩니다
                    </p>
                    <div class="flex justify-center">
                        <button
                            class="border-2 border-white  text-white block rounded-sm font-bold py-4 px-6 mr-2 flex items-center hover:bg-gray-900 hover:text-pink-500 transition ease-in-out duration-700">
                             Show me
                            </button>
                    </div>
                </div>
            </div>
        </section>
        <!--- First Image -->
        <section class="">
            <div class="container mx-auto flex px-10 py-8 items-center justify-center flex-col">
                <img class="lg:w-15/15 md:w-15/5 w-20/6 mb-10 object-cover object-center rounded" alt="hero"
                    src="{% static 'img/front.jpg'%}">
            </div>
        </section>
        <section class="text-black">
            <div class="container mx-auto flex px-5 py-24 md:flex-row flex-col items-center">
                <div class="lg:max-w-lg lg:w-full md:w-1/2 w-5/6 md:mb-0 mb-10 ">
                    <img class="object-cover object-center rounded" alt="hero"
                        src="{% static 'img/feature1.jpg'%}">
                </div>
                <div
                    class="lg:flex-grow md:w-1/2 lg:pl-24 md:pl-16 flex flex-col md:items-start md:text-left items-center text-center">
                    <h1 class="title-font sm:text-4xl text-3xl mb-4 font-medium text-black ">
                    Embrace Life
                    </h1>
                    <p class="mb-8 leading-relaxed">
                    세계적 수준의 바이오의약품 R&D 역량과 전문성을 바탕으로 새로운 패러다임을 제시할 첨단 의약품을 개발합니다
                    </p>
                    <div class="flex justify-center">
                        <button
                            class="border-2 border-black  text-black block rounded-sm font-bold py-4 px-6 mr-2 flex items-center hover:bg-white hover:text-indigo-500 transition ease-in-out duration-700">Button</button>
                    </div>
                </div>
            </div>
        </section>
        <section class="text-black">
            <div class="container mx-auto flex px-5 py-24 md:flex-row flex-col items-center">
                <div
                    class="lg:flex-grow md:w-1/2 lg:pr-24 md:pr-16 flex flex-col md:items-start md:text-left mb-16 md:mb-0 items-center text-center">
                    <h1 class="title-font sm:text-4xl text-3xl mb-4 font-medium text-black">
                    Biologics that make more sense
                    </h1>
                    <p class="mb-8 leading-relaxed">
                     FastFowardBio의 항체 바이오시밀러는 환자들에게 합리적 비용으로 고품질 바이오의약품 치료를 받을 수 있는 기회를 제공합니다
                    </p>
                    <div class="flex justify-center">
                        <button
                            class="border-2 border-black  text-black block rounded-sm font-bold py-4 px-6 mr-2 flex items-center hover:bg-white hover:text-indigo-500 transition ease-in-out duration-700">Button</button>
                    </div>
                </div>
                <div class="lg:max-w-lg lg:w-full md:w-1/2 w-5/6">
                    <img class="object-cover object-center rounded" alt="hero"
                        src="{% static 'img/feature2.jpg'%}">
                </div>
            </div>
        </section>
        <section class="text-black">
            <div class="container mx-auto flex px-5 py-24 md:flex-row flex-col items-center">
                <div class="lg:max-w-lg lg:w-full md:w-1/2 w-5/6 md:mb-0 mb-10">
                    <img class="object-cover object-center rounded" alt="hero"
                        src="{% static 'img/feature3.jpg'%}">
                </div>
                <div
                    class="lg:flex-grow md:w-1/2 lg:pl-24 md:pl-16 flex flex-col md:items-start md:text-left items-center text-center">
                    <h1 class="title-font sm:text-4xl text-3xl mb-4 font-medium text-black">
                    의약품의 개발부터 생산까지
                    </h1>
                    <p class="mb-8 leading-relaxed">
                    원활한 기술이전, 임상 및 상업 제품 제조/생산, 무균 충전(완제), 분석 테스팅 서비스를 제공하는 CDMO 파트너입니다. 고객을 만나는 순간부터 고객사 별 전담 PM팀이 제품의 개발에서 제조까지 전 과정을 함께 합니다.
                    </p>
                    <div class="flex justify-center">
                        <button
                            class="border-2 border-black  text-black block rounded-sm font-bold py-4 px-6 mr-2 flex items-center hover:bg-white hover:text-indigo-500 transition ease-in-out duration-700">Button</button>
                    </div>
                </div>
            </div>
        </section>
        <section class="text-black">
            <div class="container mx-auto flex px-5 py-24 md:flex-row flex-col items-center">
                <div
                    class="lg:flex-grow md:w-1/2 lg:pr-24 md:pr-16 flex flex-col md:items-start md:text-left mb-16 md:mb-0 items-center text-center">
                    <h1 class="title-font sm:text-4xl text-3xl mb-4 font-medium text-black">신뢰할 수 있는 파트너
                    </h1>
                    <p class="mb-8 leading-relaxed">
                     높은 수준의 우수 의약품 제조 및 품질 관리 기준(cGMP)을 준수하는 최첨단 생산 시설에서 안전하고 믿을 수 있는 임상 및 상업 바이오 의약품 개발 및 생산 서비스를 제공합니다.
                     </p>
                    <div class="flex justify-center">
                        <button
                            class="border-2 border-black  text-black block rounded-sm font-bold py-4 px-6 mr-2 flex items-center hover:bg-white hover:text-indigo-500 transition ease-in-out duration-700">Button</button>
                    </div>
                </div>
                <div class="lg:max-w-lg lg:w-full md:w-1/2 w-5/6">
                    <img class="object-cover object-center rounded" alt="hero"
                        src="{% static 'img/feature4.jpg'%}">
                </div>
            </div>
        </section>
        <section class="text-black">
            <div class="container px-5 py-24 mx-auto">
                <div class="flex flex-col text-center w-full mb-20">
                    <h1 class="text-2xl font-medium title-font mb-4 text-black">함께 세계로 함께 나아갈 팀</h1>
                    <p class="lg:w-2/3 mx-auto leading-relaxed">
                         FDA, EMA와 같은 글로벌 규제당국의 수준에 부합하기 위한 엄격한 품질관리와 최첨단 평가기법을 통한 품질 평가에 대한 기대를 모두 충족할 수 있어야만 합니다. 분석법개발팀에서는 제품 개발의 진퇴를 결정할 수 있는 분석 분야의 최전방에서, 최신 트렌드의 분석법을 직접 접하고 개발할 기회를 가질 수 있어 보람과 책임이 큰 업무 분야입니다. 책임감 있고, 적극적인 많은 신입사원분들과 함께 근무하고 싶습니다. 
                    </p>
                </div>
                <div class="text-gray-600 flex flex-wrap m-4">
                    <div class="p-4 lg:w-1/4 md:w-1/2">
                        <div class="h-full flex flex-col items-center text-center bg-gray-800 rounded-lg">
                            <img alt="team"
                                class="flex-shrink-0 rounded-t-lg w-full h-56 object-cover object-center mb-4"
                                src="{% static 'img/person1.jpg'%}">
                            <div class="w-full ">
                                <h2 class="title-font font-medium text-lg text-white">Joana Lee</h2>
                                <h3 class=" mb-3">Full Stack Developer</h3>
                            </div>
                        </div>
                    </div>
                    <div class="p-4 lg:w-1/4 md:w-1/2">
                        <div class="h-full flex flex-col items-center text-center bg-gray-800 rounded-lg">
                            <img alt="team"
                                class="flex-shrink-0 rounded-t-lg w-full h-56 object-cover object-center mb-4"
                                src="{% static 'img/person2.jpg'%}">
                            <div class="w-full ">
                                <h2 class="title-font font-medium text-lg text-white">Jhon Smith</h2>
                                <h3 class="mb-3">Marketing Director</h3>
                            </div>
                        </div>
                    </div>
                    <div class="p-4 lg:w-1/4 md:w-1/2">
                        <div class="h-full flex flex-col items-center text-center bg-gray-800 rounded-lg">
                            <img alt="team"
                                class="flex-shrink-0 rounded-t-lg w-full h-56 object-cover object-center mb-4"
                                src="{% static 'img/person3.jpg'%}">
                            <div class="w-full ">
                                <h2 class="title-font font-medium text-lg text-white">Patricia Swimm</h2>
                                <h3 class="mb-3">Product Designer</h3>
                            </div>
                        </div>
                    </div>
                    <div class="p-4 lg:w-1/4 md:w-1/2">
                        <div class="h-full flex flex-col items-center text-center bg-gray-800 rounded-lg">
                            <img alt="team"
                                class="flex-shrink-0 rounded-t-lg w-full h-56 object-cover object-center mb-4"
                                src="{% static 'img/person4.jpg'%}">
                            <div class="w-full ">
                                <h2 class="title-font font-medium text-lg text-white">Robert Willow</h2>
                                <h3 class="mb-3">UI Designer</h3>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <!--- Testimonail Section -->
        <section class="text-black">
            <div class="container px-5 py-24 mx-auto">
                <div class="xl:w-1/2 lg:w-3/4 w-full mx-auto text-center">
                    <img class="inline-block w-20 h-20 text-gray-700 mb-8" src={% static 'logo.png'%} width="45" height="45">
                    <p class="leading-relaxed text-lg">
                    인류의 행복한 삶을 위한 공존의 내일을 만들어 갑니다. 글로벌 헬스케어의 새로운 장을 열어갑니다 
                    </p>
                    <span class="inline-block h-1 w-10 rounded bg-indigo-500 mt-8 mb-6"></span>
                    <h2 class="text-black font-medium title-font tracking-wider text-sm">김우성</h2>
                    <p class="text-black">The Fresh Prince</p>
                </div>
            </div>
        </section>
        <!--- Blog Section -->
                <section class="text-black  overflow-hidden">
            <div class="container px-5 py-5 mx-auto">
                <div class="py-8 flex flex-wrap md:flex-no-wrap">
                    <h1 class="title-font sm:text-4xl text-3xl mb-4 font-medium text-black">최신 소식
                    </h1>
                </div>
                <div class="text-black my-3">
                {% for post in posts %}
                    <div class="py-8 flex flex-wrap md:flex-no-wrap">
                        <div class="md:w-64 md:mb-0 mb-6 flex-shrink-0 flex flex-col">
                            <span class="tracking-widest font-medium title-font">
                            {{ post.category }}</span>
                            <span class="mt-1 text-sm">{{ post.published_date|date:"D d M Y" }}</span>
                        </div>
                        <div class="md:flex-grow">
                            <h2 class="text-2xl font-medium text-black title-font mb-2">{{ post.title }}</h2>
                            <p class="leading-relaxed">{{ post.text|truncatewords:50  }}</p>
                            <a class="text-black-7000 inline-flex items-center mt-4" href="{% url 'page:post_detail' pk=post.pk %}">더 읽어보기 »
                            </a>
                        </div>
                    </div>
{% endfor %}
                </div>
            </div>
        </section>
{% endblock content %}

page/templates/page/nav.html
    {% load static %}
	 <header class="text-gray-700 body-font border-b border-gray-300 ">
            <div class="container mx-auto flex flex-wrap p-5 flex-col md:flex-row items-center">
                <a href="{% url 'page:index'%}"
                    class="flex title-font font-medium items-center text-gray-900 mb-4 md:mb-0">
                    <img src='{% static "logo_transparent.png" %}' width="50" height="50">
                </a>
                <nav class="md:ml-auto md:mr-auto flex flex-wrap items-center text-base justify-center">
				    <a class="mr-5 hover:text-black font-semibold my-3" href="{% url 'page:about' %}">About us</a>
                    <a class="mr-5 hover:text-black font-semibold my-3" href="{% url 'page:business' %}">Business</a>
                    <a class="mr-5 hover:text-black font-semibold my-3" href="{% url 'page:science' %}">Science</a>
                    <a class="mr-5 hover:text-black font-semibold my-3" href="{% url 'page:product' %}">Products</a>
                    <a class="mr-5 hover:text-black font-semibold my-3" href="{% url 'page:career' %}">Career</a>
                </nav>
                <a  href="{% url 'page:plan' %}" class="">
                <button class=" border-2 border-black  text-black block rounded-sm font-bold py-4 px-6 mr-2 flex items-center hover:bg-white hover:text-indigo-500 transition ease-in-out duration-700 md:mt-0">
                    See Plans
                </button>
                </a>
            </div>
        </header>
        <!---End Global Header-->

page/templates/page/post_detail.html
{% extends 'page/base.html' %}

{% block content %}
<section class="text-black">
  <div
    class="container mx-auto flex px-5 pt-24 items-center justify-center flex-col"
  >
    <div class="text-center lg:w-2/3 w-full">
      <h1
        class="title-font sm:text-4xl text-3xl mb-4 font-medium text-black font-mono"
      >
        {{ post.title }}
      </h1>
      <p class="leading-relaxed mb-8 font-normal">
        {{ post.text|linebreaksbr }}
      </p>
      <div class="flex justify-center mb-20">
              {% if post.published_date %}
            <div class="date">
                {{ post.published_date }}
            </div>
        {% endif %}
      </div>
    </div>
  </div>
</section>

{% endblock %}

page/templates/page/product.html
{% extends "page/base.html" %} 
{% load static %} 
{% block content %}


<section class="py-64">
  <div
    class="container mx-auto flex px-10 py-8 items-center justify-center flex-col"
  >
    <h1 class="text-gray-700 text-6xl title-font font-black">
      Wow, such a empty!
    </h1>
  </div>
</section>


{% endblock %}